### ISSUE TITLE
Trimming after adapter detection

### ISSUE THREAD

**Issue by gitMakeCoffee** [cihga39871/Atria#12]
Using the `--detect-adapter` flag does detect the adapters, but does not start trimming of the fastq files. The adapter sequences have to be copy-pasted into another atria command. Any way to automate this process? Thanks.

**Comment by cihga39871** [comment]
Adapter detection is the last choice because its accuracy is highly based on your data. If your data has been trimmed, the remaining adapters may not be enough for accurate guessing. We suggest using adapter detection only when you cannot find the actual adapter sequence.

Besides, Atria does not automatically trim auto-detected adapters. It is your responsibility to check whether the detected adapters are real.
    
    Those rules can be used to check the adapter results: 
    
    (1) An Illumina sequence file only has ONE adapter sequence (multiple primers are to be supported in v4). 
    
    (2) In the same batch of NGS experiments, all R1 samples should have the SAME adapter sequence, and so do R2 samples. The most prevalent adapters of R1 and R2 might be true for all your data.
