### ISSUE TITLE
OSX Release?

### ISSUE THREAD

**Issue by dbrookeUAB** [cihga39871/Atria#7]
Where do I find the  `.osx.tar.gz` file? I only see files for the linux releases.

**Comment by cihga39871** [comment]
Sorry, we no longer provide OSX release because we do not have access to x86 or M-series Mac. Please [build Atria from source](https://github.com/cihga39871/Atria/blob/master/docs/1.2.Install_from_source.md#osx). The build script is easy to follow and won't take long. Thank you for your understanding.
